### ISSUE TITLE
Not able to view on Shiny

### ISSUE THREAD

**Issue by Vidyullekha** [gpilgrim2670/SwimMap#1]
Dear Greg,

I would like to mention you that the app link is not opening. Could you please check this.

https://gpilgrim.shinyapps.io/SwimmingProject-Click/

Looking forward for your response.

Best Regards
Vidy

**Comment by gpilgrim2670** [comment]
Vidyullekha,

Seems to be working fine.  The shinyapps server can only handle so many connections at a time - perhaps that was the issue when you tried to connect.  If you can reproduce and confirm I'll do some more checking.

Best,
Greg

**Comment by Vidyullekha** [comment]
Hi Greg,

Thank you. It's working 

BR
Vidyullekha
